# =============================================================================
# ERP-SYSTEM - Ultimate PostgreSQL Fix (Must run as Administrator)
# =============================================================================
# هذا السكريبت يصلح كل مشاكل PostgreSQL تلقائياً:
#   1. يكتشف مسار PostgreSQL
#   2. يقرأ pg_hba.conf
#   3. يكتب pg_hba.conf جديد كلياً بـ trust mode + ASCII (لا BOM)
#   4. يوقف ويشغّل PostgreSQL service
#   5. يختبر الاتصال
#   6. ينشئ erp_user + databases
#   7. يشغّل النظام
# =============================================================================

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir   = Resolve-Path "$ScriptDir\.."
$BackendLog   = Join-Path $RootDir ".backend.log"
$BackendErr   = Join-Path $RootDir ".backend.err.log"
$FrontendLog  = Join-Path $RootDir ".frontend.log"
$FrontendErr  = Join-Path $RootDir ".frontend.err.log"
$FrontendDir  = Join-Path $RootDir "src\frontend"
$SettingsFile = Join-Path $RootDir "src\backend\Host\appsettings.json"

function Write-Step($msg)  { Write-Host "[*] $msg" -ForegroundColor Cyan }
function Write-Ok($msg)    { Write-Host "[+] $msg" -ForegroundColor Green }
function Write-Warn($msg)  { Write-Host "[!] $msg" -ForegroundColor Yellow }
function Write-Fail($msg)  { Write-Host "[X] $msg" -ForegroundColor Red; exit 1 }

# Check admin
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host ""
    Write-Host "[X] MUST RUN AS ADMINISTRATOR!" -ForegroundColor Red
    Write-Host "    Use FIX-POSTGRES.bat instead" -ForegroundColor Yellow
    Write-Host ""
    pause
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  ERP-SYSTEM - Ultimate Fix" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ============ 1) Find PostgreSQL ============
Write-Step "Step 1/7: Finding PostgreSQL installation..."

$pgRoot = $null
$pgData = $null
$psql = $null
$pgService = $null

$PGVersions = @(15, 16, 17)
foreach ($v in $PGVersions) {
    $root = "C:\Program Files\PostgreSQL\$v"
    if (Test-Path $root) {
        $pgRoot = $root
        $pgData = Join-Path $root "data"
        $psql = Join-Path $root "bin\psql.exe"
        $svc = Get-Service -Name "postgresql-x64-$v" -ErrorAction SilentlyContinue
        if ($svc) {
            $pgService = $svc
            Write-Ok "Found PostgreSQL $v at $root"
            break
        }
    }
}

if (-not $psql -or -not (Test-Path $psql)) {
    Write-Fail "PostgreSQL not found. Install PostgreSQL 15+ first."
}
if (-not $pgService) {
    Write-Fail "PostgreSQL service not found. Install PostgreSQL 15+ first."
}

$pgHba = Join-Path $pgData "pg_hba.conf"
if (-not (Test-Path $pgHba)) {
    Write-Fail "pg_hba.conf not found at $pgHba"
}
Write-Ok "Data dir: $pgData"
Write-Ok "psql: $psql"
Write-Ok "Service: $($pgService.Name)"

# ============ 2) Backup and rewrite pg_hba.conf ============
Write-Step "Step 2/7: Rewriting pg_hba.conf to TRUST mode..."

$backup = "$pgHba.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
Copy-Item $pgHba $backup -Force
Write-Ok "Backup: $backup"

# Create new pg_hba.conf content with trust mode everywhere
# Using ASCII encoding (no BOM!) and Unix line endings
$newContent = @"
# PostgreSQL Client Authentication Configuration File
# Auto-generated by ERP-SYSTEM Ultimate Fix on $(Get-Date)
# All local connections: TRUST (no password)

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# IPv4 local connections:
host    all             all             127.0.0.1/32            trust

# IPv6 local connections:
host    all             all             ::1/128                 trust

# ALL IPv4 addresses (matches any local IPv4):
host    all             all             0.0.0.0/0               trust

# ALL IPv6 addresses (matches any local IPv6 like ::1):
host    all             all             ::/0                    trust

# Local socket (Unix only - no effect on Windows but listed for safety):
local   all             all                                     trust

# Replication (same rules for replication user):
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
host    replication     all             0.0.0.0/0               trust
host    replication     all             ::/0                    trust
"@

# Write as ASCII (no BOM) - this is the critical fix
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($pgHba, $newContent, $utf8NoBom)
Write-Ok "pg_hba.conf rewritten (ASCII, no BOM)"

# Verify
$written = [System.IO.File]::ReadAllText($pgHba, $utf8NoBom)
$firstBytes = [System.IO.File]::ReadAllBytes($pgHba)[0..3] | ForEach-Object { '{0:X2}' -f $_ }
Write-Step "First bytes: $($firstBytes -join ' ') (should be 23=hash, NOT EF BB BF=BOM)"

# ============ 3) Restart PostgreSQL ============
Write-Step "Step 3/7: Restarting PostgreSQL service..."

# v1.0.34-Hotfix11: Use net stop/start for guaranteed restart
try {
    Write-Step "Stopping PostgreSQL (net stop)..."
    & net.exe stop $pgService.Name 2>&1 | Out-Null
    Start-Sleep 3
    $svc = Get-Service $pgService.Name
    if ($svc.Status -ne "Stopped") {
        Write-Warn "Service not stopped, trying with -Force"
        Stop-Service $pgService.Name -Force -ErrorAction SilentlyContinue
        Start-Sleep 3
    }
    Write-Ok "Stopped"

    Write-Step "Starting PostgreSQL (net start)..."
    & net.exe start $pgService.Name 2>&1 | Out-Null
    Start-Sleep 3
    $svc = Get-Service $pgService.Name
    if ($svc.Status -ne "Running") {
        Write-Warn "Service not running, trying Start-Service"
        Start-Service $pgService.Name -ErrorAction SilentlyContinue
        Start-Sleep 3
    }
    Write-Ok "Started (status: $((Get-Service $pgService.Name).Status))"
} catch {
    Write-Warn "PowerShell restart failed, using net command directly..."
    & net.exe stop $pgService.Name 2>&1 | Out-Null
    Start-Sleep 3
    & net.exe start $pgService.Name 2>&1 | Out-Null
    Start-Sleep 3
    Write-Ok "Restarted via net command"
}

# Wait for ready
Write-Step "Waiting for PostgreSQL to be ready..."
$ready = $false
for ($i = 1; $i -le 30; $i++) {
    # v1.0.34-Hotfix12: Use 127.0.0.1 explicitly to avoid IPv6 (::1) issues
    $test = & $psql -U postgres -h 127.0.0.1 -p 5432 -tAc "SELECT 1;" 2>&1
    if ($LASTEXITCODE -eq 0) {
        $ready = $true
        Write-Ok "PostgreSQL ready after ${i}s"
        break
    }
    Start-Sleep 1
}
if (-not $ready) {
    Write-Fail "PostgreSQL not ready after 30s. Check: $pgHba"
}

# ============ 4) Test connection (no password) ============
Write-Step "Step 4/7: Testing connection (no password)..."
# v1.0.34-Hotfix12: Force IPv4 (127.0.0.1) - avoids ::1 IPv6 issues
$test = & $psql -U postgres -h 127.0.0.1 -p 5432 -tAc "SELECT version();" 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Fail "Cannot connect: $test"
}
Write-Ok "Connected: $($test.Substring(0, [Math]::Min(50, $test.Length)))..."

# ============ 5) Create user and databases ============
Write-Step "Step 5/7: Creating user and databases..."

# v1.0.34-Hotfix12: Use 127.0.0.1 to avoid IPv6 routing
& $psql -U postgres -h 127.0.0.1 -p 5432 -c "DROP DATABASE IF EXISTS erp_system;" 2>&1 | Out-Null
& $psql -U postgres -h 127.0.0.1 -p 5432 -c "DROP DATABASE IF EXISTS erp_events;" 2>&1 | Out-Null
& $psql -U postgres -h 127.0.0.1 -p 5432 -c "DROP USER IF EXISTS erp_user;" 2>&1 | Out-Null

& $psql -U postgres -h 127.0.0.1 -p 5432 -c "CREATE USER erp_user WITH PASSWORD 'erp_password' SUPERUSER;" 2>&1 | Out-Null
& $psql -U postgres -h 127.0.0.1 -p 5432 -c "CREATE DATABASE erp_system OWNER erp_user;" 2>&1 | Out-Null
& $psql -U postgres -h 127.0.0.1 -p 5432 -c "CREATE DATABASE erp_events OWNER erp_user;" 2>&1 | Out-Null
Write-Ok "Created: erp_user + erp_system + erp_events"

# ============ 6) Fix appsettings.json ============
Write-Step "Step 6/7: Fixing appsettings.json..."
if (Test-Path $SettingsFile) {
    $content = Get-Content $SettingsFile -Raw
    if ($content -match "Database=neondb") {
        $new = $content -replace "Database=neondb", "Database=erp_system"
        $utf8NoBom = New-Object System.Text.UTF8Encoding $false
        [System.IO.File]::WriteAllText($SettingsFile, $new, $utf8NoBom)
        Write-Ok "Fixed"
    } else {
        Write-Ok "Already correct"
    }
}

# Fix bin/Debug copy
$binFile = Join-Path $RootDir "src\backend\Host\bin\Debug\net9.0\appsettings.json"
if (Test-Path $binFile) {
    $binContent = Get-Content $binFile -Raw
    if ($binContent -match "Database=neondb") {
        $new = $binContent -replace "Database=neondb", "Database=erp_system"
        $utf8NoBom = New-Object System.Text.UTF8Encoding $false
        [System.IO.File]::WriteAllText($binFile, $new, $utf8NoBom)
        Write-Ok "Fixed bin/Debug copy"
    }
}

# ============ 7) Install npm deps if needed ============
Write-Step "Step 7/7: Installing npm dependencies (if needed)..."
if (-not (Test-Path (Join-Path $FrontendDir "node_modules"))) {
    Push-Location $FrontendDir
    & npm install 2>&1 | Out-Null
    Pop-Location
    Write-Ok "npm done"
} else {
    Write-Ok "npm deps already installed"
}

# Stop any existing services
Get-Process -Name "dotnet","node" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep 2

# Start Backend
Write-Step "Starting Backend on :5000..."
Start-Process -FilePath "dotnet" `
    -ArgumentList "run","--project","Host","--urls","http://localhost:5000" `
    -WorkingDirectory (Join-Path $RootDir "src\backend") `
    -RedirectStandardOutput $BackendLog `
    -RedirectStandardError  $BackendErr `
    -WindowStyle Hidden

$backendUp = $false
for ($i = 1; $i -le 90; $i++) {
    try {
        $r = Invoke-WebRequest -Uri "http://localhost:5000/health" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
        if ($r.StatusCode -lt 400) { $backendUp = $true; break }
    } catch {}
    Start-Sleep 1
}
if ($backendUp) { Write-Ok "Backend up (after ${i}s)" }
else { Write-Warn "Backend not responding (check $BackendErr)" }

# Start Frontend
Write-Step "Starting Frontend on :3000..."
Start-Process -FilePath "cmd.exe" `
    -ArgumentList "/c","set NEXT_PUBLIC_API_URL=http://localhost:5000 && npm run dev" `
    -WorkingDirectory $FrontendDir `
    -RedirectStandardOutput $FrontendLog `
    -RedirectStandardError  $FrontendErr `
    -WindowStyle Hidden

$frontendUp = $false
for ($i = 1; $i -le 90; $i++) {
    try {
        $r = Invoke-WebRequest -Uri "http://localhost:3000" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
        if ($r.StatusCode -lt 400) { $frontendUp = $true; break }
    } catch {}
    Start-Sleep 1
}
if ($frontendUp) { Write-Ok "Frontend up (after ${i}s)" }
else { Write-Warn "Frontend not responding" }

Write-Host ""
if ($backendUp -and $frontendUp) {
    Write-Ok "========================================" -ForegroundColor Green
    Write-Ok "  ALL SERVICES RUNNING!" -ForegroundColor Green
    Write-Ok "========================================" -ForegroundColor Green
} else {
    Write-Warn "Some services may not be ready. Check logs."
}
Write-Host ""
Write-Host "  Frontend:  http://localhost:3000"  -ForegroundColor Cyan
Write-Host "  Backend:   http://localhost:5000"  -ForegroundColor Cyan
Write-Host "  Login:     admin@alfajr.local / Demo1234" -ForegroundColor Cyan
Write-Host ""
Write-Host "Press any key to close this window." -ForegroundColor Gray
pause
